CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE IF NOT EXISTS PACIENTES(
CPF_PACIENTE VARCHAR(15) PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
DATA_NASC DATE NOT NULL,
TELEFONE VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45));

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
COD_ESPECIALIDADE INT PRIMARY KEY,
NOME_ESPECIALIDADE VARCHAR(45));

CREATE TABLE IF NOT EXISTS MEDICOS(
CRM INT,
UF CHAR(2),
PRIMARY KEY(CRM,UF),
NOME VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
TELEFONE VARCHAR(45) NOT NULL,
DEPTO_COD_ESPEC INT NOT NULL,
CONSTRAINT DEPTO_MED FOREIGN KEY(DEPTO_COD_ESPEC)REFERENCES DEPARTAMENTOS(COD_ESPECIALIDADE));

CREATE TABLE IF NOT EXISTS CONSULTAS(
ID_CONSULTA INT PRIMARY KEY,
ANAMNESE TEXT NOT NULL,
DATA_CONS DATE NOT NULL,
HORA_CONS TIME NOT NULL,
CRM INT NOT NULL,
UF CHAR(2) NOT NULL,
CPF_PACIENTE VARCHAR(15) NOT NULL,
CONSTRAINT MED_CONS FOREIGN KEY(CRM,UF) REFERENCES MEDICOS(CRM,UF),
CONSTRAINT PAC_CONS FOREIGN KEY(CPF_PACIENTE)REFERENCES PACIENTES(CPF_PACIENTE));

insert into pacientes
(CPF_PACIENTE,NOME,DATA_NASC,TELEFONE,EMAIL)
VALUES 
("111.111.111-2","KLEBER ANDRADE","1930-2-29","5521998234541","KLEBERAND@GMAIL.COM"),
("222.222.111-2","MATHEUS MARQUES","2006-2-14","+5521982343538","matheusrlmarques@gmail.com"),
("333.333.111-4","PABLO VEGETTI","1988-10-15","+55219998765544","PABLOVEGETTI@GMAIL.COM");

INSERT INTO DEPARTAMENTOS
(COD_ESPECIALIDADE,NOME_ESPECIlIDADE)
VALUES
(1,"PEDIATRA"),
(2,"UROLOGISTA"),
(3,"CIRURGIAO");

INSERT INTO MEDICOS
(CRM, UF, NOME, EMAIL, TELEFONE, DPTO)
VALUES
("5544-0099","RS","KLEBER ANDRADE","KLEBERAND@GMAIL.COM","+5521998234541","PEDIATRA");

INSERT INTO CONSULTAS 
(CRM,UF,NOME_MED,NOME_PACIE,DATA_CONSUL,DPTO_CONSUL)
VALUES
("5544-0099","RS","KLEBER ANDRADE","PABLO VEETTI,2024-6-15","PEDIATRIA");



